# Network tools
# Documentation: https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/private-internet-access.md
services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.0
    container_name: gluetun
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
    # https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-lan-device-to-gluetun.md
      - 8888:8888/tcp
      - 8888:8888/udp
      - 8388:8388/tcp # shadowsocks
      - 8388:8388/udp # shadowsocks
      - 8191:8191/tcp # flaresolverr
    networks:
      - private
    environment:
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - SHADOWSOCKS=on
      - SHADOWSOCKS_LOG=on
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
    volumes:
      - ./config/gluetun:/gluetun
  
  flaresolverr:
    # image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    image: 21hsmw/flaresolverr:nodrivertest
    container_name: flaresolverr
    restart: always
    depends_on:
      - gluetun
    network_mode: service:gluetun
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=debug
      - DRIVER=nodriver

  tailscale:
    image: tailscale/tailscale:v1.92.4
    container_name: tailscale
    hostname: sandalphon
    restart: always
    privileged: true
    cap_add:
      - net_admin   # Required for network administration
      - sys_module  # Required for kernel module management
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      # - TS_DOMAIN_NAME=$TS_HOST_FQDN
      - TS_EXTRA_ARGS=--advertise-routes=192.168.1.0/24 --advertise-exit-node
    volumes:
      - ./config/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun

networks:
  private:
    driver:  bridge
    enable_ipv6: false